# Generated by Django 4.2.7 on 2025-11-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chepochem_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽ RUB (Российский рубль)'), ('USD', '$ USD (Доллар США)'), ('EUR', '€ EUR (Евро)'), ('KZT', '₸ KZT (Тенге)'), ('BYN', 'Br BYN (Белорусский рубль)'), ('UAH', '₴ UAH (Гривна)')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
