# Generated by Django 4.2.7 on 2025-11-15 15:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chepochem_app', '0002_alter_listing_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('auto', 'Автоматически')], default='light', max_length=10, verbose_name='Тема')),
                ('date_format', models.CharField(choices=[('DD.MM.YYYY', 'ДД.ММ.ГГГГ'), ('MM/DD/YYYY', 'ММ/ДД/ГГГГ'), ('YYYY-MM-DD', 'ГГГГ-ММ-ДД')], default='DD.MM.YYYY', max_length=20, verbose_name='Формат даты')),
                ('page_size', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)], verbose_name='Размер страницы')),
                ('saved_filters', models.JSONField(blank=True, default=dict, verbose_name='Сохраненные фильтры')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('login', 'Вход'), ('logout', 'Выход'), ('moderate', 'Модерация'), ('export', 'Экспорт'), ('import', 'Импорт')], max_length=50, verbose_name='Действие')),
                ('entity_type', models.CharField(blank=True, max_length=50, verbose_name='Тип сущности')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID сущности')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Старые данные')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Новые данные')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='chepochem_a_user_id_b3f9e7_idx'), models.Index(fields=['entity_type', 'entity_id'], name='chepochem_a_entity__00c153_idx'), models.Index(fields=['action', 'created_at'], name='chepochem_a_action_3ac9bd_idx')],
            },
        ),
    ]
